### ISSUE TITLE
Setting ttl?

### ISSUE THREAD

**Issue by enricodeleo** [jeffbski/redis-wstream#5]
Hi! Glad this library works without problems today. I was wondering if I could set a ttl key by key. Is it possible?

**Comment by jeffbski** [comment]
It doesn't currently but we could add something to the options so that it could do that. 

If you want to take a stab at doing a PR we could add it in.

**Comment by enricodeleo** [comment]
Thank you for your reply Jeff. I solved calling explicitly something like `redisClient.expire('key', 5);`  inside `.on('finish', fn)`.
I'll give a shot asap :)
